import Providers from "./utils/providers";
import Header from "./components/header";
import { NextUIProvider } from "@nextui-org/react";
import {ThemeProvider as NextThemesProvider} from "next-themes";
import "./globals.css"
import prisma from "@/prisma/client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {



  return (
    <Providers>
        <html lang="en">
          <body>
            <NextUIProvider>
              <NextThemesProvider attribute="class" defaultTheme="dark">
                <Header/>
                {children}
              </NextThemesProvider>
            </NextUIProvider>
          </body>
        </html>
    </Providers>
  );
}
