import Providers from "./utils/providers";
import Header from "./components/header";
import { NextUIProvider } from "@nextui-org/react";
import {ThemeProvider as NextThemesProvider} from "next-themes";
import "./globals.css"
import prisma from "@/prisma/client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  let isConnected

  try {
    isConnected = await prisma.$queryRaw`SELECT 1`;
    console.log(isConnected)
  } catch (error) {
    console.log(error)
  }
 


  return (
    <Providers>
        <html lang="en">
          <body>
            <NextUIProvider>
              <NextThemesProvider attribute="class" defaultTheme="dark">
                <Header/>
                {
                  isConnected ?
                  children
                  :
                  <div className="mt-[80px]">Not connected</div>
                }
              </NextThemesProvider>
            </NextUIProvider>
          </body>
        </html>
    </Providers>
  );
}
